# Generated by Django 2.0.2 on 2018-07-06 10:43
import json

from django.db import migrations


def load_data(apps, schema_editor):
    Departure = apps.get_model('departures', 'Departure')

    with open('departures.json', 'r') as f:
        data = json.load(f)

    for departure in data:
        Departure(
            name=departure['name'],
            start_date=departure['start_date'],
            finish_date=departure['finish_date'],
            category=departure['category'],
        ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('departures', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
